[package]
name = "honey-explore"
version = "0.1.4"
edition = "2021"
authors = ["Jeremy Blythe <jeremyblythe@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
askama = { version = "0.12.1", features = ["with-axum", "markdown"] }
askama_axum = "0.4.0"
axum = "0.7.2"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.12", features = ["derive"] }
dotenv = "0.15.0"
futures = "0.3.30"
glob = "0.3.1"
honeycomb-client = { git = "https://github.com/jerbly/honeycomb-client", tag = "v0.1.0" }
openssl = { version = "0.10.61", features = ["vendored"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
tokio = { version = "1.35.0", features = ["full"] }
